source 'https://rubygems.org'

ruby '~> 3.2'

gem 'sinatra', '~> 3.1'
gem 'sinatra-contrib', '~> 3.1'
gem 'mongo', '~> 2.19'
gem 'puma', '~> 6.4'
gem 'json', '~> 2.7'
gem 'rack-cors', '~> 2.0'

group :development do
  gem 'rerun', '~> 0.14'
end
